# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jose Mateo
tagline:          'Android and other stuff'
description:      I'm an Android developer at Cycle Trader. This is my personal blog where I post whatever I want. Mostly Android stuff.
url:              http://mateoj.com
baseurl:          /
googleplus:		  http://google.com/+JoseMateoA
twitter: 		  https://twitter.com/YoMat3o
linkedin: 		  http://www.linkedin.com/in/josemateoa  

excerpt_separator: <!--more-->

disqus_shortname: josemateo
author:
  name:           'Jose Mateo'
  url:            https://twitter.com/yomat3o

paginate:         5

# Custom vars
version:          2.1.0

github:
  profile:        https://github.com/j-mateo
  repo:           https://github.com/poole/hyde
