# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jose Mateo
tagline:          'Android and other stuff'
description:      Android developer at Cycle Trader. Traveling and making life better for others is our purpose in life. Not vegan. 
url:              http://mateoj.com
baseurl:          /
googleplus:		  http://google.com/+JoseMateoA
twitter: 		  https://twitter.com/YoMat3o
linkedin: 		  http://www.linkedin.com/in/josemateoa  
analytics:        UA-32304431-1

excerpt_separator: <!--more-->

disqus_shortname: josemateo
author:
  name:           'Jose Mateo'
  url:            https://twitter.com/yomat3o

paginate:         5

# Custom vars
version:          2.1.0

github:
  profile:        https://github.com/j-mateo
  repo:           https://github.com/poole/hyde
